plugins {
    id 'java'
    id 'org.openjfx.javafxplugin' version '0.1.0'
    id 'application'
    id 'eclipse'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
        vendor = JvmVendorSpec.ADOPTIUM
    }
}

dependencies {
    implementation 'de.mwvb:xmldocument:0.1.0'

    testImplementation 'junit:junit:4.12'
}

javafx {
    version = '17.0.10'
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}

project.description = 'Stechuhr - einfache Stundenerfassung'
group = 'de.mwvb.stechuhr'
version = '2.0.0'

repositories {
    mavenCentral()
}

compileJava {
    options.encoding = 'windows-1252'
}
compileTestJava {
    options.encoding = 'windows-1252'
}

application {
    mainClass = 'de.mwvb.stechuhr.StechuhrApplication'
}

// Mit diesem task wird die Anwendung gebaut. Man erhaelt dann eine doppelklickbare StandAlone-JAR.
task fatJar(type: Jar) {
    manifest {
        attributes 'Main-Class': 'de.mwvb.stechuhr.StechuhrApplication'
    }
    archiveBaseName.set(project.name)
    from { configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) } }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    with jar
}
